name: toranaWeb
on:
  workflow_run:
    workflows: ["torana"]
    types:
      - completed
  workflow_dispatch:

env:
  OUT_LINK: toranaWeb

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            auto-optimise-store = true
            experimental-features = nix-command flakes

      - uses: cachix/cachix-action@v12
        with:
          name: pain
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: build
        run: nix build .#toranaWeb --out-link $OUT_LINK -L

      - name: wasm-bindgen
        run: >
          nix develop .#toranaWeb
          -c wasm-bindgen
          --target web $OUT_LINK/bin/torana.wasm
          --out-dir www